### ISSUE TITLE
Create the first Installer for Linux.

### ISSUE THREAD

**Issue by frank-dspeed** [stealify/legacy-1-stealify-contains-bad-justjs-zerojs-stuff#116]
- [ ] We need GraalVM 
- [ ] We need Cargo
- [ ] We need ActiX
- [ ] We need es4x Java Factorys that call JS install able via npm / yarn as first version till we got actix benchmarked and working
- [ ] We need a Example App Using ActiX inside JavaScript / ECMAScript Compiled to Binary.

## Problems with the llvm rust versions
https://michaelbh.com/blog/graalvm-and-rust-1/

**Comment by frank-dspeed** [comment]
https://github.com/shyiko/jabba
